name: Publish Library to npm

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: |
          cd library
          npm install

      - name: Run tests
        run: |
          cd library
          npm test

      - name: Build library
        run: |
          cd library
          npm run build

      - name: Publish to npm
        run: |
          cd library
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
