name: "🚀 Publish Package to npm"

on:
  push:
    branches:
      - main
    paths:
      - "library/**"

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: cd library && npm install --legacy-peer-deps

      - name: Build the package
        run: cd library && npm run build

      - name: Publish to npm
        run: cd library && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
